version: '2'
services:
  postgres:
    image: postgres:9.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=application
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
